modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="flotage"
version="${file.jarVersion}"
displayName="Flotage"
authors="Nova Committee,Chemiofitor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flotage"
description='''
Are you troubled by not being able to easily set up camp at sea?
Just ues the raft!
'''

[[dependencies.flotage]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.flotage]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"

[modproperties.flotage]
catalogueImageIcon="flotage:oak_rack"
