modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="flotage"
version="${file.jarVersion}"
displayName="Flotage"
<<<<<<< Updated upstream
authors="Nova Committee,Chemiofitor"
=======
authors = "Nova Committee,Chemiofitor"

>>>>>>> Stashed changes
[[dependencies.flotage]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
