modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="flotage"
version="${file.jarVersion}"
displayName="Flotage"
authors="Nova Committee,Chemiofitor"
description='''
Floating in the sea.
'''
[[dependencies.flotage]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.flotage]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
