modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="flotage"
version="${file.jarVersion}"
displayName="Flotage"
authors="Nova Committee,Chemiofitor"

[[dependencies.flotage]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
